[package]
name = "linkerd2-http-box"
version = "0.1.0"
authors = ["Linkerd Developers <cncf-linkerd-dev@lists.cncf.io>"]
edition = "2018"
publish = false

[dependencies]
bytes = "1"
futures = "0.3"
http = "0.2"
linkerd2-error = { path = "../error" }
linkerd2-stack = { path = "../stack" }
tower = {version = "0.4", default-features = false }
pin-project = "0.4"
